run:
  timeout: 3m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
    - gofmt
    - goimports
  disable-all: false

linters-settings:
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: indent-error-flow
        severity: warning
  gofmt:
    simplify: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
