version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - revive
    - errcheck
  settings:
    revive:
      severity: warning
      rules:
        - name: exported
          severity: warning
        - name: var-naming
          severity: warning
        - name: indent-error-flow
          severity: warning

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
